volumes:
  vol_library:
services:
  lab02:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=lab02'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=root'
    volumes:
      - vol_library:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5433:5432'
